### ISSUE TITLE
Tests are hanging on Linux

### ISSUE THREAD

**Issue by replomancer** [OpenMined/syft_experimental#3]
I just realized there was a similar issue (#2 ) recently and it's closed now but it seems related to notebooks (?) and I'm also experiencing the problem with hanging tests on my Linux machine.

I think this may be why the tests are hanging: There is a difference between platforms in how Process is started by default. In Windows and macOS it's "spawn" which creates a a fresh python interpreter:
> The child process will only inherit those resources necessary to run the process objects run() method. In particular, unnecessary file descriptors and handles from the parent process will not be inherited.

In "Unix" the default is "fork". Source: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

In node_test.py I can change the order of test cases or add a new test identical to a passing one and I always see one test passing and next one hanging. Apparently some resources are not freed after NodeProcess exit method. When I switch the multiprocessing start method to "spawn", some other things are breaking, so I don't understand the whole story yet.

This is how I'm using print statements for debugging in run_class_method message in syft/src/worker/config.rs:
```rust
    fn run_class_method_message(
        &mut self,
        url: String,
        message: SyftMessage,
    ) -> Result<SyftMessage, Box<dyn std::error::Error>> {
        let request = tonic::Request::new(message);

        println!("client: run_class_method_message\n");

        let client = self.runtime.block_on(MessageClient::connect(url));
        
        println!("client: after first block\n");

        match client {
            Ok(mut _client) => {
                println!("client: second block\n");
                let resp = self.runtime.block_on(_client.send_message(request));
                println!("client: after second block\n");
                match resp {
                Ok(_response) => {
                    let message = _response.into_inner();
                    Ok(message)
                }
                Err(_err) => {
                    println!("failed to get response from client run class: {:?}", _err);
                    Err(format!("send_message Failed: {:?}", _err))?
                }
            }},
            Err(_err) => {
                println!("failed to connect to client: {:?}", _err);
                Err(format!("failed to connect to client Failed: {:?}", _err))?
            }
        }
    }
```
and send_message in message.rs:
```rust
#[tonic::async_trait]
impl Message for MyMessage {
    async fn send_message(
        &self,
        request: Request<SyftMessage>,
    ) -> Result<Response<SyftMessage>, Status> {
        // dispatch message to capability
        println!("before get_config\n");
        let config = get_config().clone();
        println!("after get config\n");
        let message = request.into_inner();
        let capability_key = message.capability.to_owned();

        println!("before config lock");
        let locked_config = config.lock().unwrap();
        println!("after config lock");
        if let Some(callback) = locked_config.capability_map.get(&capability_key) {
            let result = callback.callable.execute(message);

            match result {
                Ok(message) => Ok(Response::new(message)),
                Err(err) => Err(tonic::Status::new(
                    tonic::Code::NotFound,
                    format!(
                        "Unable to dispatch to capability {}. Error: {}",
                        &capability_key, err
                    ),
                )),
            }
        } else {
            Err(tonic::Status::new(
                tonic::Code::NotFound,
                format!("Unable to dispatch to capability: {}", &capability_key),
            ))
        }
    }
}
```
Pytest output:
```
(syft_experimental) lukasz@lukasz-XPS-15-9570:~/src/OpenMined/syft_experimental/platforms/python (dev)$ maturin develop && pytest -vvv -s
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at python
   Compiling syft_python v0.1.0 (/home/lukasz/src/OpenMined/syft_experimental/platforms/python)
    Finished dev [unoptimized + debuginfo] target(s) in 2.25s
========================================== test session starts ==========================================
platform linux -- Python 3.8.2, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /home/lukasz/.virtualenvs/syft_experimental/bin/python
cachedir: .pytest_cache
rootdir: /home/lukasz/src/OpenMined/syft_experimental/platforms/python
collected 6 items                                                                                       

tests/message_test.py::test_message_creation PASSED
tests/message_test.py::test_message_decoding ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_deserialize', 'send']
PASSED
tests/node_test.py::test_node_message Starting node on 0.0.0.0:8080
Tokio thread started
Capability registered: sum
ffi: run_class_method_message

before config lock

Tokio thread started
after config lock

client: run_class_method_message

client: after first block

client: second block

before get_config

after get config

before config lock
after config lock
client: after second block

PASSED
tests/node_test.py::test_node_message_2 Starting node on 0.0.0.0:8080
Capability registered: sum
ffi: run_class_method_message

before config lock

after config lock

client: run_class_method_message

client: after first block

client: second block

```
aaand it's hanging there :stopwatch: test_node_message_2 is just a copy of test_node_message.

So the first test passes outputting this sequence:
```
client: after first block

client: second block

before get_config

after get config

before config lock
after config lock
client: after second block
```
and the second one (which is identical to first one) hangs after this (before printing "before get_config"):
```
client: after first block

client: second block
```
so it's blocked in this line:
```rust
                let resp = self.runtime.block_on(_client.send_message(request));
```
but first thing in "send_message" should be printing another message - which doesn't happen so either send_message is not even called or it's called but the first print output there dissapears is some buffer...

aaand I just saw when I Ctrl-C he's telling me he's been waiting here for the event in start_node:
```
^CProcess Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lukasz/src/OpenMined/syft_experimental/platforms/python/tests/node_test.py", line 110, in start_node
    event.wait(1)
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 349, in wait
    self._cond.wait(timeout)
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt
```

Allright, when I started writing this I had a better story :book: I hope this is still useful for further discussion. Or maybe I will figure it out soon.

**Comment by replomancer** [comment]
Resolved by #4
